DROP TABLE PANIER

CREATE TABLE PANIER(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UTILISATEUR_ID INT NOT NULL,
	POKEMON_ID INT NOT NULL,
	POKEMON_NAME VARCHAR(50) NOT NULL,
	POKEMON_TYPE1 VARCHAR(50) NOT NULL,
	POKEMON_TYPE2 VARCHAR(50) NOT NULL,
	POKEMON_EVOLUTION VARCHAR(50) NOT NULL,
	POKEMON_PRICE FLOAT NOT NULL,
	POKEMON_DESCRIPTION VARCHAR(300) NOT NULL,
	POKEMON_IMAGE VARCHAR (300) NOT NULL
)
