DROP TABLE POKEMONS;

CREATE TABLE POKEMONS(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TYPE1 VARCHAR(50) NOT NULL,
	TYPE2 VARCHAR(50) NOT NULL,
	PRICE FLOAT NOT NULL,
	DESCRIPTION VARCHAR(300) NOT NULL,
	IMAGE VARCHAR (300) NOT NULL
)

INSERT INTO [dbo].[POKEMONS] ( [NAME], [TYPE1], [TYPE2], [PRICE], [DESCRIPTION], [IMAGE] )
VALUES
( 'Bulbizarre', 'Plante', 'Poison', 19.99, 'Bulbizarre est un Pokémon de type Plante et Poison. Il se trouve dans la région de Kanto et évolue en Herbizarre.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png' ),
( 'Herbizarre', 'Plante', 'Poison', 29.99, 'Herbizarre est un Pokémon de type Plante et Poison. Il est l''évolution de Bulbizarre et évolue en Florizarre.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png' ),
( 'Florizarre', 'Plante', 'Poison', 39.99, 'Florizarre est un Pokémon de type Plante et Poison. Il est l''évolution finale de Bulbizarre.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png' ),
( 'Salamèche', 'Feu', '', 19.99, 'Salamèche est un Pokémon de type Feu. Il se trouve dans la région de Kanto et évolue en Reptincel.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png' ),
( 'Reptincel', 'Feu', '', 29.99, 'Reptincel est un Pokémon de type Feu. Il est l''évolution de Salamèche et évolue en Dracaufeu.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png' ),
( 'Dracaufeu', 'Feu', 'Vol', 39.99, 'Dracaufeu est un Pokémon de type Feu et Vol. Il est l''évolution finale de Salamèche.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png' ),
( 'Carapuce', 'Eau', '', 19.99, 'Carapuce est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Carabaffe.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png' ),
( 'Carabaffe', 'Eau', '', 29.99, 'Carabaffe est un Pokémon de type Eau. Il est l''évolution de Carapuce et évolue en Tortank.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png' ),
( 'Tortank', 'Eau', '', 39.99, 'Tortank est un Pokémon de type Eau. Il est l''évolution finale de Carapuce.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png' ),
( 'Chenipan', 'Insecte', '', 9.99, 'Chenipan est un Pokémon de type Insecte. Il se trouve dans la région de Kanto et évolue en Chrysacier.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png' ),
( 'Chrysacier', 'Insecte', '', 14.99, 'Chrysacier est un Pokémon de type Insecte. Il est l''évolution de Chenipan et évolue en Papilusion.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png' ),
( 'Papilusion', 'Insecte', 'Vol', 19.99, 'Papilusion est un Pokémon de type Insecte et Vol. Il est l''évolution finale de Chenipan.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png' ),
( 'Aspicot', 'Insecte', 'Poison', 9.99, 'Aspicot est un Pokémon de type Insecte et Poison. Il se trouve dans la région de Kanto et évolue en Coconfort.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png' ),
( 'Coconfort', 'Insecte', 'Poison', 14.99, 'Coconfort est un Pokémon de type Insecte et Poison. Il est l''évolution d''Aspicot et peut ensuite évoluer en Dardargnan.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png' ),
( 'Dardargnan', 'Insecte', 'Poison', 29.99, 'Dardargnan est un Pokémon de type Insecte et Poison. Il est l''évolution de Coconfort.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png' ),
( 'Roucool', 'Normal', 'Vol', 9.99, 'Roucool est un Pokémon de type Normal et Vol. Il se trouve dans la région de Kanto et évolue en Roucoups.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png' ),
( 'Roucoups', 'Normal', 'Vol', 19.99, 'Roucoups est un Pokémon de type Normal et Vol. Il est l''évolution de Roucool et peut ensuite évoluer en Roucarnage.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png' ),
( 'Roucarnage', 'Normal', 'Vol', 39.99, 'Roucarnage est un Pokémon de type Normal et Vol. Il est l''évolution de Roucoups.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png' ),
( 'Rattata', 'Normal', '', 9.99, 'Rattata est un Pokémon de type Normal. Il se trouve dans la région de Kanto et évolue en Rattatac.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png' ),
( 'Rattatac', 'Normal', '', 19.99, 'Rattatac est un Pokémon de type Normal. Il est l''évolution de Rattata.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png' ),
( 'Piafabec', 'Normal', 'Vol', 14.99, 'Piafabec est un Pokémon de type Normal et Vol. Il se trouve dans la région de Kanto et évolue en Rapasdepic.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png' ),
( 'Rapasdepic', 'Normal', 'Vol', 34.99, 'Rapasdepic est un Pokémon de type Normal et Vol. Il est l''évolution de Piafabec.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png' ),
( 'Abo', 'Poison', '', 9.99, 'Abo est un Pokémon de type Poison. Il se trouve dans la région de Kanto et évolue en Arbok.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png' ),
( 'Arbok', 'Poison', '', 29.99, 'Arbok est un Pokémon de type Poison. Il est l''évolution de Abo.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png' ),
( 'Pikachu', 'Electrique', '', 19.99, 'Pikachu est un Pokémon de type Electrique. Il se trouve dans la région de Kanto et évolue en Raichu.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png' ),
( 'Raichu', 'Electrique', '', 29.99, 'Raichu est un Pokémon de type Electrique. Il est l''évolution de Pikachu.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png' ),
( 'Sabelette', 'Sol', '', 19.99, 'Sabelette est un Pokémon de type Sol. Il se trouve dans la région de Kanto et évolue en Sablaireau.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png' ),
( 'Sablaireau', 'Sol', '', 29.99, 'Sablaireau est un Pokémon de type Sol. Il est l''évolution de Sabelette.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png' ),
( 'Nidoran', 'Poison', '', 19.99, 'Nidoran est un Pokémon de type Poison. Il se trouve dans la région de Kanto et évolue en Nidorina.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png' ),
( 'Nidorina', 'Poison', '', 29.99, 'Nidorina est un Pokémon de type Poison. Elle est l''évolution de Nidoran.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png' ),
( 'Nidoqueen', 'Poison', 'Sol', 49.99, 'Nidoqueen est un Pokémon de type Poison et Sol. Elle est l''évolution de Nidorina.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png' ),
( 'Nidoran', 'Poison', '', 19.99, 'Nidoran est un Pokémon de type Poison. Il se trouve dans la région de Kanto et évolue en Nidorino.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png' ),
( 'Nidorino', 'Poison', '', 29.99, 'Nidorino est un Pokémon de type Poison. Il est l''évolution de Nidoran.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png' ),
( 'Nidoking', 'Poison', 'Sol', 49.99, 'Nidoking est un Pokémon de type Poison et Sol. Il est l''évolution de Nidorino.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png' ),
( 'Mélofée', 'Fée', '', 19.99, 'Mélofée est un Pokémon de type Fée. Il se trouve dans la région de Kanto et évolue en Mélodelfe.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png' ),
( 'Mélodelfe', 'Fée', '', 29.99, 'Mélodelfe est un Pokémon de type Fée. Il est l''évolution de Mélofée.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png' ),
( 'Goupix', 'Feu', '', 19.99, 'Goupix est un Pokémon de type Feu. Il se trouve dans la région de Kanto et évolue en Feunard.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png' ),
( 'Feunard', 'Feu', '', 29.99, 'Feunard est un Pokémon de type Feu. Il est l''évolution de Goupix.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png' ),
( 'Rondoudou', 'Normal', 'Fée', 19.99, 'Rondoudou est un Pokémon de type Normal et Fée. Il se trouve dans la région de Kanto et évolue en Grodoudou.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png' ),
( 'Grodoudou', 'Normal', 'Fée', 29.99, 'Grodoudou est un Pokémon de type Normal et Fée. Il est l''évolution de Rondoudou.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png' ),
( 'Nosferapti', 'Poison', 'Vol', 19.99, 'Nosferapti est un Pokémon de type Poison et Vol. Il se trouve dans la région de Kanto et évolue en Nosferalto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png' ),
( 'Nosferalto', 'Poison', 'Vol', 29.99, 'Nosferalto est un Pokémon de type Poison et Vol. Il est l''évolution de Nosferapti.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png' ),
( 'Mystherbe', 'Plante', 'Poison', 19.99, 'Mystherbe est un Pokémon de type Plante et Poison. Il se trouve dans la région de Kanto et évolue en Ortide.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png' ),
( 'Ortide', 'Plante', 'Poison', 29.99, 'Ortide est un Pokémon de type Plante et Poison. Il est l''évolution de Mystherbe.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png' ),
( 'Rafflesia', 'Plante', 'Poison', 34.99, 'Rafflesia est un pokémon de type Plante et Poison. Il est l''évolution de Ortide', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png'),
( 'Paras', 'Insecte', 'Plante', 19.99, 'Paras est un Pokémon de type Insecte et Plante. Il se trouve dans la région de Kanto et évolue en Parasect.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png' ),
( 'Parasect', 'Insecte', 'Plante', 29.99, 'Parasect est un Pokémon de type Insecte et Plante. Il est l''évolution de Paras.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png' ),
( 'Mimitoss', 'Insecte', 'Poison', 19.99, 'Mimitoss est un Pokémon de type Insecte et Poison. Il se trouve dans la région de Kanto et évolue en Aéromite.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png' ),
( 'Aéromite', 'Insecte', 'Poison', 29.99, 'Aéromite est un Pokémon de type Insecte et Poison. Il est l''évolution de Mimitoss.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png' ),
( 'Taupiqueur', 'Sol', '', 19.99, 'Taupiqueur est un Pokémon de type Sol. Il se trouve dans la région de Kanto et évolue en Triopikeur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png' ),
( 'Triopikeur', 'Sol', '', 29.99, 'Triopikeur est un Pokémon de type Sol. Il est l''évolution de Taupiqueur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png' ),
( 'Miaouss', 'Normal', '', 19.99, 'Miaouss est un Pokémon de type Normal. Il se trouve dans la région de Kanto et évolue en Persian.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png' ),
( 'Persian', 'Normal', '', 29.99, 'Persian est un Pokémon de type Normal. Il est l''évolution de Miaouss.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png' ),
( 'Psykokwak', 'Eau', 'Psy', 19.99, 'Psykokwak est un Pokémon de type Eau et Psy. Il se trouve dans la région de Kanto et évolue en Akwakwak.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png' ),
( 'Akwakwak', 'Eau', 'Psy', 29.99, 'Akwakwak est un Pokémon de type Eau et Psy. Il est l''évolution de Psykokwak.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png' ),
( 'Férosinge', 'Combat', '', 19.99, 'Férosinge est un Pokémon de type Combat. Il se trouve dans la région de Kanto et évolue en Colossinge.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png' ),
( 'Colossinge', 'Combat', '', 29.99, 'Colossinge est un Pokémon de type Combat. Il est l''évolution de Férosinge.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png' ),
( 'Caninos', 'Feu', '', 19.99, 'Caninos est un Pokémon de type Feu. Il se trouve dans la région de Kanto et évolue en Arcanin.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png' ),
( 'Arcanin', 'Feu', '', 29.99, 'Arcanin est un Pokémon de type Feu. Il est l''évolution de Caninos.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png' ),
( 'Ptitard', 'Eau', '', 19.99, 'Ptitard est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Têtarte.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png' ),
( 'Têtarte', 'Eau', '', 29.99, 'Têtarte est un Pokémon de type Eau. Il est l''évolution de Ptitard et peut évoluer en Tartard.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png' ),
( 'Tartard', 'Eau', 'Combat', 39.99, 'Tartard est un Pokémon de type Eau et Combat. Il est l''évolution de Têtarte.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png' ),
( 'Abra', 'Psy', '', 14.99, 'Abra est un Pokémon de type Psy. Il se trouve dans la région de Kanto et évolue en Kadabra.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png' ),
( 'Kadabra', 'Psy', '', 29.99, 'Kadabra est un Pokémon de type Psy. Il est l''évolution d''Abra et peut évoluer en Alakazam.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png' ),
( 'Alakazam', 'Psy', '', 49.99, 'Alakazam est un Pokémon de type Psy. Il est l''évolution de Kadabra.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png' ),
( 'Machoc', 'Combat', '', 19.99, 'Machoc est un Pokémon de type Combat. Il se trouve dans la région de Kanto et évolue en Machopeur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png' ),
( 'Machopeur', 'Combat', '', 29.99, 'Machopeur est un Pokémon de type Combat. Il est l''évolution de Machoc et peut évoluer en Mackogneur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png' ),
( 'Mackogneur', 'Combat', '', 49.99, 'Mackogneur est un Pokémon de type Combat. Il est l''évolution de Machopeur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png' ),
( 'Chétiflor', 'Plante', 'Poison', 14.99, 'Chétiflor est un Pokémon de type Plante et Poison. Il se trouve dans la région de Kanto et évolue en Boustiflor.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png' ),
( 'Boustiflor', 'Plante', 'Poison', 29.99, 'Boustiflor est un Pokémon de type Plante et Poison. Il est l''évolution de Chétiflor.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png' ),
( 'Empiflor', 'Plante', 'Poison', 39.99, 'Empiflor est un Pokémon de type Plante et Poison. Il est l''évolution de Boustiflor.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png' ),
( 'Tentacool', 'Eau', 'Poison', 19.99, 'Tentacool est un Pokémon de type Eau et Poison. Il se trouve dans la région de Kanto et évolue en Tentacruel.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png' ),
( 'Tentacruel', 'Eau', 'Poison', 29.99, 'Tentacruel est un Pokémon de type Eau et Poison. Il est l''évolution de Tentacool.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png' ),
( 'Racaillou', 'Roche', 'Sol', 19.99, 'Racaillou est un Pokémon de type Roche et Sol. Il se trouve dans la région de Kanto et évolue en Gravalanch.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png' ),
( 'Gravalanch', 'Roche', 'Sol', 29.99, 'Gravalanch est un Pokémon de type Roche et Sol. Il est l''évolution de Racaillou.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png' ),
( 'Grolem', 'Roche', 'Sol', 39.99, 'Grolem est un Pokémon de type Roche et Sol. Il est l''évolution de Gravalanch.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png' ),
( 'Ponyta', 'Feu', '', 19.99, 'Ponyta est un Pokémon de type Feu. Il se trouve dans la région de Kanto et évolue en Galopa.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png' ),
( 'Galopa', 'Feu', '', 29.99, 'Galopa est un Pokémon de type Feu. Il est l''évolution de Ponyta.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png' ),
( 'Ramoloss', 'Eau', 'Psy', 19.99, 'Ramoloss est un Pokémon de type Eau et Psy. Il se trouve dans la région de Kanto et évolue en Flagadoss.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png' ),
( 'Flagadoss', 'Eau', 'Psy', 29.99, 'Flagadoss est un Pokémon de type Eau et Psy. Il est l''évolution de Ramoloss.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png' ),
( 'Magnéti', 'Electrik', 'Acier', 19.99, 'Magnéti est un Pokémon de type Electrik et Acier. Il se trouve dans la région de Kanto et évolue en Magnéton.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png' ),
( 'Magnéton', 'Electrik', 'Acier', 29.99, 'Magnéton est un Pokémon de type Electrik et Acier. Il est l''évolution de Magnéti.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png' ),
( 'Canarticho', 'Normal', 'Vol', 19.99, 'Canarticho est un Pokémon de type Normal et Vol. Il se trouve dans la région de Kanto et n''évolue pas.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png' ),
( 'Doduo', 'Normal', 'Vol', 19.99, 'Doduo est un Pokémon de type Normal et Vol. Il se trouve dans la région de Kanto et évolue en Dodrio.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png' ),
( 'Dodrio', 'Normal', 'Vol', 29.99, 'Dodrio est un Pokémon de type Normal et Vol. Il est l''évolution de Doduo.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png' ),
( 'Otaria', 'Eau', '', 19.99, 'Otaria est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Lamantine.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png' ),
( 'Lamantine', 'Eau', 'Glace', 29.99, 'Lamantine est un Pokémon de type Eau et Glace. Il est l''évolution d''Otaria.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png' ),
( 'Tadmorv', 'Poison', '', 19.99, 'Tadmorv est un Pokémon de type Poison. Il se trouve dans la région de Kanto et évolue en Grotadmorv.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png' ),
( 'Grotadmorv', 'Poison', '', 29.99, 'Grotadmorv est un Pokémon de type Poison. Il est l''évolution de Tadmorv.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png' ),
( 'Kokiyas', 'Eau', '', 19.99, 'Kokiyas est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Crustabri.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png' ),
( 'Crustabri', 'Eau', 'Glace', 29.99, 'Crustabri est un Pokémon de type Eau et Glace. Il est l''évolution de Kokiyas.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png' ),
( 'Fantominus', 'Spectre', 'Poison', 19.99, 'Fantominus est un Pokémon de type Spectre et Poison. Il se trouve dans la région de Kanto et évolue en Spectrum.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png' ),
( 'Spectrum', 'Spectre', 'Poison', 29.99, 'Spectrum est un Pokémon de type Spectre et Poison. Il est l''évolution de Fantominus.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png' ),
( 'Ectoplasma', 'Spectre', 'Poison', 29.99, 'Ectoplasma est un Pokémon de type Spectre et Poison. Il est l''évolution de Spectrum.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png' ),
( 'Onix', 'Roche', 'Sol', 29.99, 'Onix est un Pokémon de type Roche et Sol. Il se trouve dans la région de Kanto et évolue en Steelix.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png' ),
( 'Soporifik', 'Psy', '', 19.99, 'Soporifik est un Pokémon de type Psy. Il se trouve dans la région de Kanto et évolue en Hypnomade.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png' ),
( 'Hypnomade', 'Psy', '', 29.99, 'Hypnomade est un Pokémon de type Psy. Il est l''évolution de Soporifik.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png' ),
( 'Krabby', 'Eau', '', 19.99, 'Krabby est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Krabboss.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png' ),
( 'Krabboss', 'Eau', '', 29.99, 'Krabboss est un Pokémon de type Eau. Il est l''évolution de Krabby.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png' ),
( 'Voltorbe', 'Electrique', '', 19.99, 'Voltorbe est un Pokémon de type Electrique. Il se trouve dans la région de Kanto et évolue en Électrode.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png' ),
( 'Électrode', 'Electrique', '', 29.99, 'Électrode est un Pokémon de type Electrique. Il est l''évolution de Voltorbe.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png' ),
( 'Noeunoeuf', 'Plante', 'Psy', 19.99, 'Noeunoeuf est un Pokémon de type Plante et Psy. Il se trouve dans la région de Kanto et évolue en Noadkoko.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png' ),
( 'Noadkoko', 'Plante', 'Psy', 29.99, 'Noadkoko est un Pokémon de type Plante et Psy. Il est l''évolution de Noeunoeuf.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png' ),
( 'Osselait', 'Sol', '', 19.99, 'Osselait est un Pokémon de type Sol. Il évolue en Ossatueur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png' ),
( 'Ossatueur', 'Sol', '', 29.99, 'Ossatueur est un Pokémon de type Sol. Il est l''évolution de Osselait.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png' ),
( 'Kicklee', 'Combat', '', 19.99, 'Kicklee est un Pokémon de type Combat. Il se trouve dans la région de Kanto et n''a pas d''évolution.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png' ),
( 'Tygnon', 'Combat', '', 19.99, 'Tygnon est un Pokémon de type Combat. Il se trouve dans la région de Kanto et n''a pas d''évolution.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png' ),
( 'Excelangue', 'Normal', '', 29.99, 'Excelangue est un Pokémon de type Normal. Il se trouve dans la région de Kanto et évolue en Colossinge.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png' ),
( 'Smogo', 'Poison', '', 19.99, 'Smogo est un Pokémon de type Poison. Il se trouve dans la région de Kanto et évolue en Smogogo.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png' ),
( 'Smogogo', 'Poison', '', 29.99, 'Smogogo est un Pokémon de type Poison. Il est l''évolution de Smogo.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png' ),
( 'Rhinocorne', 'Sol', 'Roche', 19.99, 'Rhinocorne est un Pokémon de type Sol et Roche. Il se trouve dans la région de Kanto et évolue en Rhinoféros.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png' ),
( 'Rhinoféros', 'Sol', 'Roche', 29.99, 'Rhinoféros est un Pokémon de type Sol et Roche. Il est l''évolution de Rhinocorne.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png' ),
( 'Leveinard', 'Normal', '', 29.99, 'Leveinard est un Pokémon de type Normal. Il se trouve dans la région de Kanto et évolue en Leuphorie.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png' ),
( 'Saquedeneu', 'Plante', '', 19.99, 'Saquedeneu est un Pokémon de type Plante. Il se trouve dans la région de Kanto et n''a pas d''évolution.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png' ),
( 'Kangourex', 'Normal', '', 29.99, 'Kangourex est un Pokémon de type Normal. Il se trouve dans la région de Kanto et n''a pas d''évolution.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png' ),
( 'Hypotrempe', 'Eau', '', 19.99, 'Hypotrempe est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Hypocéan.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png' ),
( 'Hypocéan', 'Eau', '', 29.99, 'Hypocéan est un Pokémon de type Eau. Il est l''évolution de Hypotrempe.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png' ),
( 'Poissirène', 'Eau', '', 19.99, 'Poissirène est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Poissoroy.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png' ),
( 'Poissoroy', 'Eau', '', 29.99, 'Poissoroy est un Pokémon de type Eau. Il est l''évolution de Poissirène.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png' ),
( 'Stari', 'Eau', '', 19.99, 'Stari est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Staross.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png' ),
( 'Staross', 'Eau', 'Psy', 29.99, 'Staross est un Pokémon de type Eau et Psy. Il est l''évolution de Stari.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png' ),
( 'M. Mime', 'Psy', 'Fee', 29.99, 'M. Mime est un Pokémon de type Psy et Fée. Il se trouve dans la région de Kanto et n''a pas d''évolution connue.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png' ),
( 'Insécateur', 'Insecte', 'Vol', 29.99, 'Insécateur est un Pokémon de type Insecte et Vol. Il est l''évolution de Chenipan.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png' ),
( 'Lippoutou', 'Glace', 'Psy', 29.99, 'Lippoutou est un Pokémon de type Glace et Psy. Il se trouve dans la région de Kanto et n''a pas d''évolution connue.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png' ),
( 'Élektek', 'Électrique', '', 29.99, 'Élektek est un Pokémon de type Électrique. Il se trouve dans la région de Kanto et n''a pas d''évolution connue.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png' ),
( 'Magmar', 'Feu', '', 29.99, 'Magmar est un Pokémon de type Feu. Il est l''évolution de Magby et peut évoluer en Maganon avec l''aide d''une pierre de Feu.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png' ),
( 'Scarabrute', 'Insecte', '', 19.99, 'Scarabrute est un Pokémon de type Insecte. Il se trouve dans la région de Kanto et est l''évolution de Insécateur.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png' ),
( 'Tauros', 'Normal', '', 19.99, 'Tauros est un Pokémon de type Normal. Il se trouve dans la région de Kanto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png' ),
( 'Magicarpe', 'Eau', '', 9.99, 'Magicarpe est un Pokémon de type Eau. Il se trouve dans la région de Kanto et évolue en Léviator.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png' ),
( 'Léviator', 'Eau', 'Vol', 49.99, 'Léviator est un Pokémon de type Eau et Vol. Il est l''évolution de Magicarpe.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png' ),
( 'Lokhlass', 'Eau', 'Glace', 49.99, 'Lokhlass est un Pokémon de type Eau et Glace. Il se trouve dans la région de Kanto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png' ),
( 'Métamorph', 'Normal', '', 9.99, 'Métamorph est un Pokémon de type Normal. Il se trouve dans la région de Kanto et peut se transformer en n''importe quel autre Pokémon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png' ),
( 'Évoli', 'Normal', '', 19.99, 'Évoli est un Pokémon de type Normal. Il se trouve dans la région de Kanto et peut évoluer en plusieurs formes différentes.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png' ),
( 'Aquali', 'Eau', '', 29.99, 'Aquali est un Pokémon de type Eau. Il est l''une des évolutions possibles d''Évoli.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png' ),
( 'Voltali', 'Électrique', '', 29.99, 'Voltali est un Pokémon de type Électrique. Il est l''une des évolutions possibles d''Évoli.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png' ),
( 'Pyroli', 'Feu', '', 29.99, 'Pyroli est un Pokémon de type Feu. Il est l''une des évolutions possibles d''Évoli.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png' ),
( 'Porygon', 'Normal', '', 29.99, 'Porygon est un Pokémon de type Normal. Il a été créé artificiellement par des humains.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png' ),
( 'Amonita', 'Roche', 'Eau', 19.99, 'Amonita est un Pokémon de type Roche et Eau. Il se trouve dans la région de Kanto et évolue en Amonistar.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png' ),
( 'Amonistar', 'Roche', 'Eau', 29.99, 'Amonistar est un Pokémon de type Roche et Eau. Il est l''évolution d''Amonita.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png' ),
( 'Kabuto', 'Roche', 'Eau', 19.99, 'Kabuto est un Pokémon de type Roche et Eau. Il se trouve dans la région de Kanto et évolue en Kabutops.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png' ),
( 'Kabutops', 'Roche', 'Eau', 29.99, 'Kabutops est un Pokémon de type Roche et Eau. Il est l''évolution de Kabuto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png' ),
( 'Ptéra', 'Roche', 'Vol', 29.99, 'Ptéra est un Pokémon de type Roche et Vol. Il est l''évolution de Ptera.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png' ),
( 'Ronflex', 'Normal', '', 29.99, 'Ronflex est un Pokémon de type Normal. Il se trouve dans la région de Kanto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png' ),
( 'Artikodin', 'Glace', 'Vol', 49.99, 'Artikodin est un Pokémon de type Glace et Vol. C''est l''un des trois oiseaux légendaires de Kanto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png' ),
( 'Électhor', 'Electrique', 'Vol', 49.99, 'Électhor est un Pokémon de type Electrique et Vol. C''est l''un des trois oiseaux légendaires de Kanto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png' ),
( 'Sulfura', 'Feu', 'Vol', 49.99, 'Sulfura est un Pokémon de type Feu et Vol. C''est l''un des trois oiseaux légendaires de Kanto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png' ),
( 'Minidraco', 'Dragon', '', 19.99, 'Minidraco est un Pokémon de type Dragon. Il se trouve dans la région de Kanto et évolue en Draco.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png' ),
( 'Draco', 'Dragon', '', 29.99, 'Draco est un Pokémon de type Dragon. Il est l''évolution de Minidraco.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png' ),
( 'Dracolosse', 'Dragon', 'Vol', 39.99, 'Dracolosse est un Pokémon de type Dragon et Vol. Il est l''évolution de Draco.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png' ),
( 'Mewtwo', 'Psy', '', 59.99, 'Mewtwo est un Pokémon légendaire de type Psy. Il a été créé génétiquement à partir du DNA de Mew.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png' ),
( 'Mew', 'Psy', '', 79.99, 'Mew est un Pokémon légendaire de type Psy. Il est considéré comme le plus rare des Pokémon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png' )