DROP TABLE IF EXISTS UTILISATEURS

CREATE TABLE UTILISATEURS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	LASTNAME VARCHAR(50) NOT NULL,
	FIRSTNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL
)

INSERT INTO [dbo].[UTILISATEURS] ( [LASTNAME], [FIRSTNAME], [EMAIL], [PASSWORD] )
VALUES
(N'Brugghe', N'Benjamin', N'Adresse@email.com', N'Azerty')
